const DURATION_MOVIES = 40;

const MOBILE_RESOLUTION = 576;
const TABLET_RESOLUTION = 992;

const DESKTOP_COUNT = 12;
const TABLET_COUNT = 8;
const MOBILE_COUNT = 5;

const DESKTOP_MORE_COUNT = 3;
const TABLET_MORE_COUNT = 2;
const MOBILE_MORE_COUNT = 2;



export {
  DURATION_MOVIES,
  MOBILE_RESOLUTION,
  TABLET_RESOLUTION,
  DESKTOP_COUNT,
  TABLET_COUNT,
  MOBILE_COUNT,
  DESKTOP_MORE_COUNT,
  TABLET_MORE_COUNT,
  MOBILE_MORE_COUNT,
};